### ISSUE TITLE
error messages for nested comments

### ISSUE THREAD

**Issue by joshuaselsky** [universityofcalifornia/NeXt#350] opened 2016-01-07 18:39 UTC
For nested comments, error messages are not displayed when the comment is invalid or cannot be stored on the server.

**Comment by pmeads** [comment] 2016-01-09 00:00
I'm not able to reproduce this yet. When I reply to a comment and send only a "𐐒" (4 bytes), I do get the error "Mysql2::Error: Incorrect string value: '\xF0\x90\x90\x92' for column 'body' at row 1: INSERT INTO `comments` (`body`, `commentable_id`, `commentable_type`, `created_at`, `lft`, `parent_id`, `rgt`, `updated_at`, `user_id`) VALUES ('𐐒', 4, 'Idea', '2016-01-08 23:55:15', 45, 72, 46, '2016-01-08 23:55:15', 6) "

 but it is displaying properly at the top in the flash error section as it should

**Comment by ctrance** [comment] 2016-01-14 22:37
@joshuaselsky - I see error message when submitting a blank or emoticons nested comments. I'm closing this.

**Closed by ctrance** 2016-01-14 22:37 UTC
Labels: ready for testing
