### ISSUE TITLE
Vote for Top Collaborators

### ISSUE THREAD

**Issue by ebollens** [universityofcalifornia/NeXt#20] opened 2014-12-19 18:59 UTC
Let's have some sort of a leaderboard, maybe all-time and over some shorter duration like the last month, related to promoting individuals who are collaborating heavily.

This was raised on the NeXT call.

**Comment by rrocchio** [comment] 2015-05-01 08:40
I believe that this is a duplicate of People Leader Boards...

**Closed** 2015-11-12 17:12 UTC
Labels: duplicate
