### ISSUE TITLE
[Projects] - Changes to the Project Form ( Limits, Help and validation)

### ISSUE THREAD

**Issue by rrocchio** [universityofcalifornia/NeXt#77] opened 2015-06-08 19:01 UTC
We need to add and communicate the limits of each field to the users, so that it is easy to know from the project creator's perspective how much detail to go into before filling out the form.

1) For example the field "Pitch" should be limited to either 500 words or 2000 characters
I think that we should put these limits on the bottom lower right hand side of each input field.

2) We should find a way to give users examples, perhaps little black bubbles with question marks in them to allow for a help-pop-up overlay for each field

3) The current bottom 4 fields, seem to all require website URLs.  We could validate for these, or allow for users to upload documents for these items.

**Comment by ctmcintyre** [comment] 2015-06-08 19:04
Agreed on 1).  Let's also keep field lengths shorter than longer (less is more).

**Comment by krozett** [comment] 2015-06-22 23:42
I think input placeholders are the quickest way to convey example information, but I also did the help bubbles too for explanations of the fields.

**Comment by ctrance** [comment] 2015-09-14 22:13
@krozett Some text fields don't have max chars limit: Problem Statement and Description.

**Comment by ctrance** [comment] 2015-09-14 22:15
@krozett - Accdg. to #76 Problem Statement has no limitations, so only Description is missing the limit chars info.

**Comment by krozett** [comment] 2015-09-15 02:35
@ctrance That is by design, Description is also unlimited.

**Comment by ctrance** [comment] 2015-09-18 15:27
Got it! I'm closing this then.

**Closed by ctrance** 2015-09-18 15:27 UTC
Labels: Med Priority, READY FOR TESTING, size 6, UCLA
